KUI-1447: Fetch data from Ladok mellanlager
KTH/kurs-pm-admin-web pull request #290
Opened 2024-09-17 12:12 UTC by axelbjo

- Removed gradeScales (formattedGradeScales) since it is not used in the project
- Added Ladok implementation for title, credits and schoolCode
- Removed unused functions in koppsCourseData.js

Still need to check if there are Ladok alternatives for the fields belonging to termsWithCourseRounds.
Do not merge yet.

2024-09-18 13:57 UTC, karlandindrakryggen requested changes

2024-09-20 14:20 UTC, karlandindrakryggen commented on server/controllers/adminCtrl.js
> +      const courseData = { ladokCourseRounds, ladokData, body }
Is `body` (result from getKoppsCourseData) used anywhere now? It looks like it isn't, so maybe call to getKoppsCourseData can be removed.

2024-09-20 14:24 UTC, karlandindrakryggen commented on server/controllers/adminCtrl.js
> +      const courseData = { ladokCourseRounds, ladokData, body }
We also need to look into the other use of `getKoppsCourseData`. It is exposed in server.js as an api route (/api/memo-admin/getKoppsCourseDataByCourse). What I can find it is only used in [handleBack in AdminPage.js](https://github.com/KTH/kurs-pm-admin-web/blob/93a969fd834afbc0fa9ac5f9eb4e0ca0515d502f/public/js/app/views/AdminPage.jsx#L215), but I don't understand why. 
So we need to understand if its needed and then either
- remove it
- or replace it with call to ladok as well

2024-09-20 14:27 UTC, karlandindrakryggen commented on common-context/createCommonContextFunctions.js
> +            state: 'APPROVED',
Jag har skapat jira https://kth-se.atlassian.net/browse/KUI-1492

2024-09-20 14:34 UTC, karlandindrakryggen commented on common-context/createCommonContextFunctions.js
> +    })
I think it can be good to create a few unit tests for this logic (and maybe break it out to it's own function to make it easier to tests)

2024-09-25 07:02 UTC, karlandindrakryggen approved these changes
Bra jobbat! 👏

2024-09-25 07:14 UTC, amirhossein-haerian approved these changes

2024-09-25 12:58 UTC, merged